name: brokenlink

on: 
  schedule:
  - cron: '*/15 * * * *'

jobs: 
  linkChecker:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Link Checker
      uses: peter-evans/link-checker@v1.0.1
      with:
        args: -v -r ./v6
       
    # issue is created and assigned to me, but the error is not logged in the description
    # - name: Create Issue From File
    #   uses: peter-evans/create-issue-from-file@v1.0.1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     ISSUE_TITLE: broken link or image found
    #     ISSUE_CONTENT_FILEPATH: ./example-content/output.md
    #     ISSUE_ASSIGNEES: ch264
    