on:
  pull_request:
    branches:
    - master
name: Testing linkcheck
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: md-linkcheck
      uses: ocular-d/md-linkcheck-action@1.0.1