# add config from DavidAnsons Markdownlint library config
# https://github.com/igorshubovych/markdownlint-cli

{
  "default": true,
  "MD007": { "indent": 4 },
  "MD026": false,
  "MD014": false,
  "MD041": false,
  "MD033": false,
  "MD035": false,
  "MD040": false,
  "MD045": false,
  "no-hard-tabs": false,
  "whitespace": false,
}