# add config from DavidAnsons Markdownlint library config
# https://github.com/igorshubovych/markdownlint-cli

{
  "default": true,
  "MD007": { "indent": 4 },
  "MD026": false,
  "MD014": false,
  "no-hard-tabs": false,
  "whitespace": false,
}