# I am not sure if this actually checks the right links

name: brokenlink

on: 
  schedule:
  # - cron: '*/13 * * * *'

jobs: 
  linkChecker:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Link Checker
      uses: peter-evans/link-checker@v1.0.1
      with:
        args: -v -r ./v6
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_TITLE: Link Checker Report
        ISSUE_CONTENT_FILEPATH: ./link-checker/out.md
        ISSUE_LABELS: report, automated issue

    # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     ISSUE_TITLE: broken link or image found
    #     ISSUE_CONTENT_FILEPATH: ./link-checker/out.md
    #     ISSUE_ASSIGNEES: ch264
    
