name: brokenlink

on: 
  push:
    branches: linkchecker

jobs: 
  linkChecker:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    # - name: Broken-Links-Crawler
    #   uses: ScholliYT/Broken-Links-Crawler-Action@v2.0.0

    - name: Link Checker
      uses: peter-evans/link-checker@v1.0.1
      with:
        args: -v -r *

    # - name: run link checker
    #   run: blc https://learning.getpostman-beta.com/ -ro