name: CI

on: 
  push, pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: Run a multi-line script
      run: |
        npm install
        node markdownlint.js
