name: CI

on: 
  push:
    branches:
    - pull3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: lint all markdownfiles
      run: |
        npm install
        node_modules/.bin/markdownlint ./ --ignore node_modules --ignore v5
        '/(?:s3\.amazonaws\.com)' ? echo 'not this url' 


# name: checks for image urls
#       # runs: 
#         # main: dist/index.js
#         # - regExp:" /(?:s3\.amazonaws\.com)(?:echo\:\ stop)/"
#   if: /(?:s3\.amazonaws\.com)
#   run: |
#     echo Please use new image url

# name: 
#   run: 

