name: CI

on: 
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: lint all markdownfiles
      run: |
        npm install
        # lint all files
        # node_modules/.bin/markdownlint ./ --ignore node_modules --ignore v5 
        # lint only files that changed on branch
        # git ls-files -m > temp && while read p; do node_modules/.bin/markdownlint "$p"; done < temp | rm temp
        # lint all recently modified md files by running bash script
        # npm run test
        files=`git ls-files -m`
        for x in $files;
        do
          if [ ${x: -3} == ".md" ]
          then
            node_modules/.bin/markdownlint $x
          fi
        done

