name: checkerrrr

on:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '*/60 * * * *'
  # paths:
  # - '*.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: md-linkcheck
      uses: ocular-d/md-linkcheck-action@1.0.2

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_TITLE: Link Checker Report
        ISSUE_CONTENT_FILEPATH: ./link-checker/out.md
        ISSUE_LABELS: report, automated issue