name: manually re-running actions

on: 
  repository_dispatch:
    types: prod-deploy

jobs:

  manual_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: prod-deploy
        run: echo prod-deploy
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          ref: master
      - name: lint all markdownfiles
        run: |
          npm install
          npm run test
