name: manually re-running actions

on: repository_dispatch

jobs:

  manual_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          ref: master
      - name: lint all markdownfiles
        run: |
          npm install
          npm run test
