name: URL

on: 
  push:
    branches: 
    - pull3

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check for image url
      run: |
        if grep -lr 's3.amazonaws.com' ./v6 ; 
        then echo "s3 references found"; 
          exit 1; 
        else echo "no s3 references found"; fi
