name: URL

on: 
  push:
    branches: 
    - pull3

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check for image url
      run: |
        grep -lr 's3'
        echo grep ran
